import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import {getFirestore, collection, addDoc} from "firebase/firestore";
import {useState} from "react";
import {async} from "@firebase/util";
import {app} from "@/service/firebase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <li className="m-auto mb-[16px] w-10/12 h-[152px] bg-green-200">1</li>
        <li className="m-auto mb-[16px] w-10/12 h-[152px] bg-green-200">2</li>
        <li className="m-auto mb-[16px] w-10/12 h-[152px] bg-green-200">3</li>
        <li className="m-auto mb-[16px] w-10/12 h-[152px] bg-green-200">4</li>
        <li className="m-auto mb-[16px] w-10/12 h-[152px] bg-green-200">5</li>
      </ul>

      <div>ㅎㅎ</div>
    </>
  );
}
